services:
  bulma_db:
    image: postgres:17.4
    restart: always
    env_file: .env.docker
    ports:
      - 5432:5432
    volumes:
      - bulma_db_data:/var/lib/postgresql/data

  bulma_db_test:
    image: postgres:17.4
    restart: always
    env_file: .env.test.docker
    ports:
      - 54321:5432

volumes:
  bulma_db_data:
